spring:
  config:
    activate:
      on-profile: dev
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hackernews

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    git:
      enabled: true

animeQuote:
  enabled: false
  collector-interval-millisecond: 5000

hackernews:
  enabled: false
  collector-interval-millisecond: 5000
  topic: hackernews-item-id
