spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/spreading
    username: spreading
    password: spreading
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hackernews
  jpa:
    show-sql: true # Display SQL queries when run Hibernate functions

# Expose only actuator endpoints "/health" and "/info"
# Only Git data is provided in "/info" endpoint
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    git:
      enabled: true

animeQuote:
  enabled: false
  collector-interval-millisecond: 5000

hackernews:
  enabled: true
  collector-interval-millisecond: 5000
  topic: hackernews-item-id
