spring:
  config:
    activate:
      on-profile: dev
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hackernews

animeQuote:
  enabled: false
  collector-interval-millisecond: 5000

hackernews:
  enabled: true
  collector-interval-millisecond: 5000
  topic: hackernews-item-id
